services:
  trakt-tv-now-playing:
    image: ghcr.io/alexraskin/trakt-tv-now-playing:${GIT_COMMIT_HASH:-latest}
    networks:
      - traefik-public
    secrets:
      - trakt-api-key
    environment:
      - TRAKT_API_KEY=/run/secrets/trakt-api-key
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.trakt-tv-now-playing-https.rule=Host(`trakt.alexraskin.com`) || Host(`www.trakt.alexraskin.com`) || Host(`trakt.twizy.sh`) || Host(`www.trakt.twizy.sh`)"
        - "traefik.http.routers.trakt-tv-now-playing-https.entrypoints=https"
        - "traefik.http.routers.trakt-tv-now-playing-https.tls=true"
        - "traefik.http.routers.trakt-tv-now-playing-https.tls.certresolver=le"

        - "traefik.http.routers.trakt-tv-now-playing-https.middlewares=redirect-trakt-alexraskin,redirect-trakt-twizy"

        - "traefik.http.middlewares.redirect-trakt-alexraskin.redirectregex.regex=^https?://trakt\\.alexraskin\\.com(.*)"
        - "traefik.http.middlewares.redirect-trakt-alexraskin.redirectregex.replacement=https://www.trakt.alexraskin.com$${1}"
        - "traefik.http.middlewares.redirect-trakt-alexraskin.redirectregex.permanent=true"

        - "traefik.http.middlewares.redirect-trakt-twizy.redirectregex.regex=^https?://trakt\\.twizy\\.sh(.*)"
        - "traefik.http.middlewares.redirect-trakt-twizy.redirectregex.replacement=https://www.trakt.twizy.sh$${1}"
        - "traefik.http.middlewares.redirect-trakt-twizy.redirectregex.permanent=true"

        - "traefik.http.services.trakt-tv-now-playing-https.loadbalancer.server.port=4000"

      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  traefik-public:
    external: true

secrets:
  trakt-api-key:
    external: true
